### ISSUE TITLE
IEV rendering rules

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-data#6]
Rendering of Preferred and Deprecated synonyms (192-02-24, en)

>In the IEV the following are permitted according to today’s rules:
>- 2 preferred terms = rendered in bold (in the data Term and Synonym1)
>- admitted terms (in the data Synonym2 and Synonym3) = since a couple of years, rendered in lightface and Status=”Admitted”; before (and this is what you see in IEV 103 and 192), rendered in bold and Status = blank or “Preferred” – see for example 192-01-10 where the rendering of “LCC” and “CCV” according to today’s rules shall be in light face and not bold as was correct at the time that this standard was approved
>- deprecated terms = rendered in lightface with a prefix “DEPRECATED:” (Status = “Deprecated”) – see for example 192-01-11
 
Rendering of SOURCE (192-13-08)

> In standards and the IEV: prefix “SOURCE:”.
> In normal standards the source is delimited by square brackets; in the IEV there are no delimiters.
 
Rendering of numbered list items within definitions (192-13-03)
> This is an old entry – according to today’s rules it is not permissible since it contains 2 definitions. Can put 1) 2) or 1. 2.or 1st definition: 2nd definition.
 
Rendering of symbol in MathML (192-08-06, en)
> In the IEV, if a symbol is in the field “Symbol” and when rendered is placed between the IEV ref and the en language section, the symbol is “international”. See the snapshot for the rendering of this symbol in 192-08-06:

![image013](https://user-images.githubusercontent.com/11865/78649430-03d50e00-78f0-11ea-9be3-221863b1de8e.jpg)

 
> Rendering of symbol in image (192-08-06, fr)

Images, MathML, math in HTML, are all rendered the same way.

Math should be rendered the same way whichever language section it is in.

Ideally all math should be marked up in MathML.

**Comment by ronaldtse** [comment]
Ping @opoudjis @strogonoff in case you didn't see this.

**Comment by opoudjis** [comment]
Of these:

* Rendering of Preferred and Deprecated synonyms

No real difference from ISO, although IEC stylesheet renders DEPRECATED in smaller font.

* Rendering of SOURCE

Done.

* Rendering of numbered list items within definitions

"1) ...." is not a numbered list rendering in the example, it is an inline paragraph. Any ordered lists in IEV will be no different to what they are throughout IEC and ISO, with letter numbering (a, b). If IEV is to be an exception, it will need to be justified; this seems to be an ad hoc matter, and better handled by just prefaced "1)".

* Rendering of symbol in MathML

Interposing a symbol between the term number and the English term would involve a markup change, which is out of scope of tonight's activity for https://github.com/metanorma/metanorma-iec/issues/1

**Comment by ronaldtse** [comment]
> "1) ...." is not a numbered list rendering in the example, it is an inline paragraph. Any ordered lists in IEV will be no different to what they are throughout IEC and ISO, with letter numbering (a, b). If IEV is to be an exception, it will need to be justified; this seems to be an ad hoc matter, and better handled by just prefaced "1)".

I think the point is they used to support multiple definitions (as in a dictionary) and still have some data like this. But this is not important for now, though.

Thanks!

**Comment by opoudjis** [comment]
https://www.iec.ch/standardsdev/resources/draftingpublications/writing_formatting/IEC_template/pdf/IEV.dot%20styles.pdf

**Comment by strogonoff** [comment]
Looks like IEV doesn’t render NOTE in all caps.

Anyway, the glossary management app is more explicit about most of it—terms are marked as “preferred”, “admitted”, etc. without the need of figuring out what bold or regular font weights might mean.

I wonder to which extend can concepts in the app look differently than their final rendered form without causing complaints.

**Comment by ronaldtse** [comment]
@strogonoff all IEC/ISO terms render Notes as:

* `Note to entry...`
* `Note N to entry: ...`

The `NOTE: ...` is only used in content text, never in definitions.

**Comment by ronaldtse** [comment]
> I wonder to which extend can concepts in the app look differently than their final rendered form without causing complaints.

I don't think the actual style is most important but they would like to see a similar structure shown so that it is not confusing for them.

**Comment by strogonoff** [comment]
> @strogonoff all IEC/ISO terms render Notes as:
> 
> * `Note to entry...` (if only one)
> * `Note N to entry: ...` (if more than one)
> 
> The `NOTE: ...` is only used in content text, never in definitions.

I recall being explicitly asked to show notes to definition as NOTEs, but perhaps I misunderstood the request…

**Comment by strogonoff** [comment]
> > I wonder to which extend can concepts in the app look differently than their final rendered form without causing complaints.
> 
> I don't think the actual style is most important but they would like to see a similar structure shown so that it is not confusing for them.

There are multiple users and one app that aims to address the needs of them all, so it’s inevitable that different things would appear new to different users…
